#!/bin/bash

# 目录
mkdir -p Scripts/Ruleset
mkdir -p Scripts/{QuantumultX,Stash,Surge}/ruleset

# 合并
{
    curl -L "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Reject.list"
    echo ""
    curl -L "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Reject/Advertising.list"
    echo ""
    curl -L "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Reject/Malicious.list"
    echo ""
    curl -L "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Reject/Tracking.list"
    echo ""
    curl -L "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list"
    echo ""
    curl -L "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list"
    echo ""
    curl -L "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list"
} > Scripts-repo/Ruleset/AdBlockLite.list

{
    curl -L "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list"
    echo ""
    curl -L "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/gfw.txt"
} > Scripts-repo/Ruleset/Global.list

# 独立
curl -L -o Scripts-repo/Ruleset/AdBlock.list "https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge.txt"
curl -L -o Scripts-repo/Ruleset/Advertising.list "https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules.list"
curl -L -o Scripts-repo/Ruleset/CNCIDR4.list "https://raw.githubusercontent.com/Hackl0us/GeoIP2-CN/release/CN-ip-cidr.txt"
curl -L -o Scripts-repo/Ruleset/CNCIDR6.list "https://raw.githubusercontent.com/Masaiki/GeoIP2-CN/release/CN-ip-cidr.txt"
curl -L -o Scripts-repo/Ruleset/PROXY.list "https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Proxy.yaml"

curl -L -o Scripts-repo/Ruleset/AmazonIP.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AmazonIp.list"
curl -L -o Scripts-repo/Ruleset/ChinaIPv4.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list"
curl -L -o Scripts-repo/Ruleset/ChinaIPv6.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIpV6.list"
curl -L -o Scripts-repo/Ruleset/Easylist.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list"
curl -L -o Scripts-repo/Ruleset/Privacy.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list"

curl -L -o Scripts-repo/Ruleset/ChinaASN.list "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/ChinaASN/ChinaASN_Resolve.list"
curl -L -o Scripts-repo/Ruleset/ChinaIPBGP.list "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/ChinaIPsBGP/ChinaIPsBGP.list"
curl -L -o Scripts-repo/Ruleset/ChinaIPMax.list "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/ChinaIPs/ChinaIPs.list"
curl -L -o Scripts-repo/Ruleset/ChinaMax.list "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax.list"
curl -L -o Scripts-repo/Ruleset/ChinaMediaMax.list "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list"
curl -L -o Scripts-repo/Ruleset/GlobalMax.list "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.list"
curl -L -o Scripts-repo/Ruleset/GlobalMediaMax.list "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list"

curl -L -o Scripts-repo/Ruleset/CNCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/cncidr.txt"
curl -L -o Scripts-repo/Ruleset/DIRECT.list "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/direct.txt"
curl -L -o Scripts-repo/Ruleset/GreatFireWall.list "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/gfw.txt"
curl -L -o Scripts-repo/Ruleset/PROXY.list "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/proxy.txt"
curl -L -o Scripts-repo/Ruleset/REJECT.list "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/reject.txt"

# curl -L -o Scripts-repo/Ruleset/AECIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/ae.txt"
# curl -L -o Scripts-repo/Ruleset/ALCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/al.txt"
# curl -L -o Scripts-repo/Ruleset/AMCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/am.txt"
# curl -L -o Scripts-repo/Ruleset/ARCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/ar.txt"
# curl -L -o Scripts-repo/Ruleset/ATCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/at.txt"
# curl -L -o Scripts-repo/Ruleset/AUCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/au.txt"
# curl -L -o Scripts-repo/Ruleset/AZCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/az.txt"
# curl -L -o Scripts-repo/Ruleset/BDCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/bd.txt"
# curl -L -o Scripts-repo/Ruleset/BECIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/be.txt"
# curl -L -o Scripts-repo/Ruleset/BGCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/bg.txt"
# curl -L -o Scripts-repo/Ruleset/BOCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/bo.txt"
# curl -L -o Scripts-repo/Ruleset/BRCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/br.txt"
# curl -L -o Scripts-repo/Ruleset/BSCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/bs.txt"
# curl -L -o Scripts-repo/Ruleset/BYCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/by.txt"
# curl -L -o Scripts-repo/Ruleset/CACIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/ca.txt"
# curl -L -o Scripts-repo/Ruleset/CHCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/ch.txt"
# curl -L -o Scripts-repo/Ruleset/CLCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cl.txt"
# curl -L -o Scripts-repo/Ruleset/CNCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cn.txt"
# curl -L -o Scripts-repo/Ruleset/COCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/co.txt"
# curl -L -o Scripts-repo/Ruleset/CRCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cr.txt"
# curl -L -o Scripts-repo/Ruleset/CYCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cy.txt"
# curl -L -o Scripts-repo/Ruleset/CZCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cz.txt"
# curl -L -o Scripts-repo/Ruleset/DECIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/de.txt"
# curl -L -o Scripts-repo/Ruleset/DKCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/dk.txt"
# curl -L -o Scripts-repo/Ruleset/DOCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/do.txt"
# curl -L -o Scripts-repo/Ruleset/ECCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/ec.txt"
# curl -L -o Scripts-repo/Ruleset/EECIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/ee.txt"
# curl -L -o Scripts-repo/Ruleset/EGCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/eg.txt"
# curl -L -o Scripts-repo/Ruleset/ESCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/es.txt"
# curl -L -o Scripts-repo/Ruleset/FRCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/fr.txt"
# curl -L -o Scripts-repo/Ruleset/GBCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/gb.txt"
# curl -L -o Scripts-repo/Ruleset/GECIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/ge.txt"
# curl -L -o Scripts-repo/Ruleset/GRCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/gr.txt"
# curl -L -o Scripts-repo/Ruleset/GTCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/gt.txt"
# curl -L -o Scripts-repo/Ruleset/HKCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/hk.txt"
# curl -L -o Scripts-repo/Ruleset/HNCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/hn.txt"
# curl -L -o Scripts-repo/Ruleset/HRCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/hr.txt"
# curl -L -o Scripts-repo/Ruleset/HUCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/hu.txt"
# curl -L -o Scripts-repo/Ruleset/JOCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/jo.txt"
# curl -L -o Scripts-repo/Ruleset/JPCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/jp.txt"
# curl -L -o Scripts-repo/Ruleset/KECIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/ke.txt"
# curl -L -o Scripts-repo/Ruleset/KHCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/kh.txt"
# curl -L -o Scripts-repo/Ruleset/KRCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/kr.txt"
# curl -L -o Scripts-repo/Ruleset/KWCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/kw.txt"
# curl -L -o Scripts-repo/Ruleset/KZCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/kz.txt"
# curl -L -o Scripts-repo/Ruleset/LBCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/lb.txt"
# curl -L -o Scripts-repo/Ruleset/LUCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/lu.txt"
# curl -L -o Scripts-repo/Ruleset/LVCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/lv.txt"
# curl -L -o Scripts-repo/Ruleset/MACIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/ma.txt"
# curl -L -o Scripts-repo/Ruleset/MDCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/md.txt"
# curl -L -o Scripts-repo/Ruleset/MKCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/mk.txt"
# curl -L -o Scripts-repo/Ruleset/MMCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/mm.txt"
# curl -L -o Scripts-repo/Ruleset/MNCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/mn.txt"
# curl -L -o Scripts-repo/Ruleset/MTCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/mt.txt"
# curl -L -o Scripts-repo/Ruleset/MXCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/mx.txt"
# curl -L -o Scripts-repo/Ruleset/MYCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/my.txt"
# curl -L -o Scripts-repo/Ruleset/NGCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/ng.txt"
# curl -L -o Scripts-repo/Ruleset/NLCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/nl.txt"
# curl -L -o Scripts-repo/Ruleset/NOCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/no.txt"
# curl -L -o Scripts-repo/Ruleset/NPCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/np.txt"
# curl -L -o Scripts-repo/Ruleset/NZCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/nz.txt"
# curl -L -o Scripts-repo/Ruleset/PACIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/pa.txt"
# curl -L -o Scripts-repo/Ruleset/PECIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/pe.txt"
# curl -L -o Scripts-repo/Ruleset/PHCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/ph.txt"
# curl -L -o Scripts-repo/Ruleset/PKCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/pk.txt"
# curl -L -o Scripts-repo/Ruleset/PLCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/pl.txt"
# curl -L -o Scripts-repo/Ruleset/PRCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/pr.txt"
# curl -L -o Scripts-repo/Ruleset/PTCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/pt.txt"
# curl -L -o Scripts-repo/Ruleset/PYCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/py.txt"
# curl -L -o Scripts-repo/Ruleset/ROCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/ro.txt"
# curl -L -o Scripts-repo/Ruleset/RSCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/rs.txt"
# curl -L -o Scripts-repo/Ruleset/RUCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/ru.txt"
# curl -L -o Scripts-repo/Ruleset/SACIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/sa.txt"
# curl -L -o Scripts-repo/Ruleset/SCCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/sc.txt"
# curl -L -o Scripts-repo/Ruleset/SECIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/se.txt"
# curl -L -o Scripts-repo/Ruleset/SGCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/sg.txt"
# curl -L -o Scripts-repo/Ruleset/SKCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/sk.txt"
# curl -L -o Scripts-repo/Ruleset/THCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/th.txt"
# curl -L -o Scripts-repo/Ruleset/TRCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/tr.txt"
# curl -L -o Scripts-repo/Ruleset/TWCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/tw.txt"
# curl -L -o Scripts-repo/Ruleset/TZCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/tz.txt"
# curl -L -o Scripts-repo/Ruleset/UACIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/ua.txt"
# curl -L -o Scripts-repo/Ruleset/USCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/us.txt"
# curl -L -o Scripts-repo/Ruleset/UZCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/uz.txt"
# curl -L -o Scripts-repo/Ruleset/VECIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/ve.txt"
# curl -L -o Scripts-repo/Ruleset/VNCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/vn.txt"
# curl -L -o Scripts-repo/Ruleset/ZACIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/za.txt"
# curl -L -o Scripts-repo/Ruleset/TNCIDR.list "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/tn.txt"

curl -L -o Scripts-repo/QuantumultX/Ruleset/AdBlock.list "https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge.txt"
curl -L -o Scripts-repo/Stash/Ruleset/AdBlock.yaml "https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge.txt"
curl -L -o Scripts-repo/Surge/Ruleset/AdBlock.list "https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge.txt"

curl -L -o Scripts-repo/QuantumultX/Ruleset/Advertising.list "https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules.list"
curl -L -o Scripts-repo/Stash/Ruleset/Advertising.yaml "https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules.list"
curl -L -o Scripts-repo/Surge/Ruleset/Advertising.list "https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules.list"